## Problem 1


In [2]:
import numpy as np

arr = np.random.randint(1, 51, (5, 4))
print("Original Array:\n", arr)

anti_diag = [arr[i, -i-1] for i in range(min(arr.shape))]
print("Anti-diagonal (top-right to bottom-left):", anti_diag)

row_max = np.max(arr, axis=1)
print("Maximum in each row:", row_max)

mean_val = np.mean(arr)
filtered = arr[arr <= mean_val]
print("Array Mean:", mean_val)
print("Elements less than or equal to mean:", filtered)

def numpy_boundary_traversal(matrix):
    top = list(matrix[0])
    right = [matrix[i][-1] for i in range(1, matrix.shape[0]-1)]
    bottom = list(matrix[-1][::-1])
    left = [matrix[i][0] for i in range(matrix.shape[0]-2, 0, -1)]
    return top + right + bottom + left

print("Boundary traversal (clockwise from top-left):", numpy_boundary_traversal(arr))


Original Array:
 [[39 50 43 31]
 [27 30  2 41]
 [19 31 25 45]
 [19 23 21 11]
 [29  3 28 16]]
Anti-diagonal (top-right to bottom-left): [31, 2, 31, 19]
Maximum in each row: [50 41 45 23 29]
Array Mean: 26.65
Elements less than or equal to mean: [ 2 19 25 19 23 21 11  3 16]
Boundary traversal (clockwise from top-left): [39, 50, 43, 31, 41, 45, 11, 16, 28, 3, 29, 19, 19, 27]


## Problem 2


In [3]:
arr = np.round(np.random.uniform(0, 10, 20), 2)
print("Original Array (rounded to 2 decimals):", arr)

print("Minimum value:", np.min(arr))
print("Maximum value:", np.max(arr))
print("Median value:", np.median(arr))

arr[arr < 5] = arr[arr < 5] ** 2
print("Array after squaring elements less than 5:", arr)

def numpy_alternate_sort(array):
    array = np.sort(array)
    result = []
    i, j = 0, len(array) - 1
    while i <= j:
        result.append(array[i])
        if i != j:
            result.append(array[j])
        i += 1
        j -= 1
    return np.array(result)

print("Array sorted in alternating min-max order:", numpy_alternate_sort(arr))


Original Array (rounded to 2 decimals): [6.81 8.41 5.1  7.13 5.22 2.83 9.35 8.44 6.99 3.07 9.51 9.7  2.66 1.58
 7.74 9.69 6.76 2.25 9.28 5.52]
Minimum value: 1.58
Maximum value: 9.7
Median value: 6.9
Array after squaring elements less than 5: [6.81   8.41   5.1    7.13   5.22   8.0089 9.35   8.44   6.99   9.4249
 9.51   9.7    7.0756 2.4964 7.74   9.69   6.76   5.0625 9.28   5.52  ]
Array sorted in alternating min-max order: [2.4964 9.7    5.0625 9.69   5.1    9.51   5.22   9.4249 5.52   9.35
 6.76   9.28   6.81   8.44   6.99   8.41   7.0756 8.0089 7.13   7.74  ]


## Problem3

In [4]:
import pandas as pd

names = [f"Student{i}" for i in range(10)]
subjects = ["Math", "Physics", "Chem", "Bio", "CS"] * 2
scores = np.random.randint(50, 101, 10)

df = pd.DataFrame({'Name': names, 'Subject': subjects, 'Score': scores, 'Grade': ''})
df['Grade'] = pd.cut(df['Score'], bins=[0, 59, 69, 79, 89, 100], labels=['F', 'D', 'C', 'B', 'A'])

print("Student DataFrame with Grades:\n", df)

print("Sorted by Score (Descending):\n", df.sort_values(by='Score', ascending=False))

print("Average score per subject:\n", df.groupby('Subject')['Score'].mean())

def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

print("Students with Grade A or B:\n", pandas_filter_pass(df))


Student DataFrame with Grades:
        Name  Subject  Score Grade
0  Student0     Math     87     B
1  Student1  Physics     63     D
2  Student2     Chem     69     D
3  Student3      Bio     95     A
4  Student4       CS     91     A
5  Student5     Math     58     F
6  Student6  Physics     67     D
7  Student7     Chem     69     D
8  Student8      Bio    100     A
9  Student9       CS     78     C
Sorted by Score (Descending):
        Name  Subject  Score Grade
8  Student8      Bio    100     A
3  Student3      Bio     95     A
4  Student4       CS     91     A
0  Student0     Math     87     B
9  Student9       CS     78     C
2  Student2     Chem     69     D
7  Student7     Chem     69     D
6  Student6  Physics     67     D
1  Student1  Physics     63     D
5  Student5     Math     58     F
Average score per subject:
 Subject
Bio        97.5
CS         84.5
Chem       69.0
Math       72.5
Physics    65.0
Name: Score, dtype: float64
Students with Grade A or B:
        Name Subj

## Problem4

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

reviews = ["Good movie"] * 50 + ["Bad movie"] * 50
sentiments = ["positive"] * 50 + ["negative"] * 50
df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model = MultinomialNB()
model.fit(X_train, y_train)

pred = model.predict(X_test)
print("Naive Bayes Test Accuracy:", accuracy_score(y_test, pred))

def predict_review_sentiment(model, vectorizer, review):
    vec = vectorizer.transform([review])
    return model.predict(vec)[0]

print("Prediction for 'Amazing movie':", predict_review_sentiment(model, vectorizer, "Amazing movie"))


Naive Bayes Test Accuracy: 1.0
Prediction for 'Amazing movie': negative


## Problem5

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

feedback = ["Nice product"] * 50 + ["Bad service"] * 50
labels = ["good"] * 50 + ["bad"] * 50
df = pd.DataFrame({'Text': feedback, 'Label': labels})

vectorizer = TfidfVectorizer(max_features=300, lowercase=True, stop_words='english')
X = vectorizer.fit_transform(df['Text'])
y = df['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
model = LogisticRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)
print("Precision (for class 'good'):", precision_score(y_test, pred, pos_label='good'))
print("Recall (for class 'good'):", recall_score(y_test, pred, pos_label='good'))
print("F1-score (for class 'good'):", f1_score(y_test, pred, pos_label='good'))

def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

print("Vectorized 'Bad quality' review:", text_preprocess_vectorize(["Bad quality"], vectorizer).toarray())


Precision (for class 'good'): 1.0
Recall (for class 'good'): 1.0
F1-score (for class 'good'): 1.0
Vectorized 'Bad quality' review: [[1. 0. 0. 0.]]
